# In this file, every section corresponds to a header file.
# A corresponding binding file will be created in $OUT_DIR.

headers = [
    "blapit.h",
    "nss.h",
    "seccomon.h",
    "secoidt.h",
    "prtypes.h",
    "prerror.h",
    "pk11pub.h",
    "pkcs11t.h",
]
enums = [
    "PK11Origin",
    "SECOidTag",
    "SECStatus",
    "SECItemType",
]
types = [
    "PRBool",
    "PRInt32",
    "PRUint32",
    "PRErrorCode",
    "NSSInitContext",
    "NSSInitParameters",
    "SECItem",
    "SECOidTag",
    "SECStatus",
    "CK_NSS_HKDFParams",
    "CK_ATTRIBUTE_TYPE",
    "CK_MECHANISM_TYPE",
    "PK11Context",
    "PK11SlotInfo",
    "PK11SymKey",
    "PK11Origin",
]
opaque = [
    "NSSInitContext",
    "NSSInitParameters",
    "PK11Context",
    "PK11SlotInfo",
    "PK11SymKey",
]
variables = [
    "NSS_INIT_FORCEOPEN",
    "NSS_INIT_NOCERTDB",
    "NSS_INIT_NOMODDB",
    "NSS_INIT_OPTIMIZESPACE",
    "NSS_INIT_READONLY",
    "CKA_SIGN",
    "CKA_WRAP",
    "CKM_SHA256_HMAC",
    "CKM_SHA512_HMAC",
    "CKM_NSS_HKDF_SHA256",
    "HASH_LENGTH_MAX",
]
