[package]
name = "rc_crypto"
version = "0.1.0"
authors = ["Edouard Oger <eoger@fastmail.com>"]
edition = "2018"
license = "ISC"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
failure = "0.1.5"
failure_derive = "0.1.5"

[target.'cfg(not(target_os = "ios"))'.dependencies]
nss_sys = { path = "nss_sys" }

[target.'cfg(target_os = "ios")'.dependencies]
ring = "0.14.5"

[dev-dependencies]
hex = "0.3.2"
